name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build_image:
    name: ${{ matrix.manylinux_base }}_${{ matrix.rust_version }}_${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - manylinux_base: manylinux_2_28
            rust_version: 1.85.0
            platform: x86_64
            ntl_version: 11.5.1
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/simple-crypto/${{ matrix.manylinux_base }}_${{ matrix.platform }}-clang:rust-${{ matrix.rust_version}}
          build-args: |
            MANYLINUX_BASE=${{ matrix.manylinux_base }}
            RUST_VERSION=${{ matrix.rust_version }}
            PLATFORM=${{ matrix.platform }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
